// <auto-generated />
namespace limingallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserAvatarModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAvatarModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201709100407193_User-Avatar-Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
